// constants/indianStates.js
export const indianStates = [
  { code: 'AN', name: 'Andaman & Nicobar', vacancies: 120, latestResult: 'APSC 2025' },
  { code: 'AP', name: 'Andhra Pradesh', vacancies: 3400, latestResult: 'APPSC Group 1' },
  { code: 'AR', name: 'Arunachal Pradesh', vacancies: 180, latestResult: 'APPSC 2025' },
  { code: 'AS', name: 'Assam', vacancies: 1200, latestResult: 'APSC CCE 2025' },
  { code: 'BR', name: 'Bihar', vacancies: 5600, latestResult: 'BPSC 67th' },
  { code: 'CH', name: 'Chandigarh', vacancies: 340, latestResult: 'CHD Admin 2025' },
  { code: 'CG', name: 'Chhattisgarh', vacancies: 2100, latestResult: 'CGPSC 2025' },
  { code: 'DL', name: 'Delhi', vacancies: 4200, latestResult: 'DSSSB TGT 2025' },
  { code: 'GA', name: 'Goa', vacancies: 280, latestResult: 'Goa PSC 2025' },
  { code: 'GJ', name: 'Gujarat', vacancies: 3800, latestResult: 'GPSC Class 1-2' },
  { code: 'HR', name: 'Haryana', vacancies: 2400, latestResult: 'HSSC CET 2025' },
  { code: 'HP', name: 'Himachal Pradesh', vacancies: 1100, latestResult: 'HPPSC 2025' },
  { code: 'JK', name: 'Jammu & Kashmir', vacancies: 1800, latestResult: 'JKPSC KAS 2025' },
  { code: 'JH', name: 'Jharkhand', vacancies: 2800, latestResult: 'JPSC 2025' },
  { code: 'KA', name: 'Karnataka', vacancies: 4100, latestResult: 'KPSC KAS 2025' },
  { code: 'KL', name: 'Kerala', vacancies: 2200, latestResult: 'Kerala PSC 2025' },
  { code: 'LA', name: 'Ladakh', vacancies: 90, latestResult: 'Ladakh Admin 2025' },
  { code: 'MP', name: 'Madhya Pradesh', vacancies: 5200, latestResult: 'MPPSC 2025' },
  { code: 'MH', name: 'Maharashtra', vacancies: 6100, latestResult: 'MPSC 2025' },
  { code: 'MN', name: 'Manipur', vacancies: 320, latestResult: 'MPSC 2025' },
  { code: 'ML', name: 'Meghalaya', vacancies: 240, latestResult: 'MPSC 2025' },
  { code: 'MZ', name: 'Mizoram', vacancies: 180, latestResult: 'MPSC 2025' },
  { code: 'NL', name: 'Nagaland', vacancies: 210, latestResult: 'NPSC 2025' },
  { code: 'OD', name: 'Odisha', vacancies: 2900, latestResult: 'OPSC 2025' },
  { code: 'PB', name: 'Punjab', vacancies: 2600, latestResult: 'PPSC 2025' },
  { code: 'RJ', name: 'Rajasthan', vacancies: 7200, latestResult: 'RPSC RAS 2025' },
  { code: 'SK', name: 'Sikkim', vacancies: 150, latestResult: 'SPSC 2025' },
  { code: 'TN', name: 'Tamil Nadu', vacancies: 3600, latestResult: 'TNPSC Group 1' },
  { code: 'TS', name: 'Telangana', vacancies: 2800, latestResult: 'TSPSC 2025' },
  { code: 'TR', name: 'Tripura', vacancies: 280, latestResult: 'TPSC 2025' },
  { code: 'UP', name: 'Uttar Pradesh', vacancies: 8500, latestResult: 'UPPSC PCS 2025' },
  { code: 'UK', name: 'Uttarakhand', vacancies: 1400, latestResult: 'UKPSC 2025' },
  { code: 'WB', name: 'West Bengal', vacancies: 3200, latestResult: 'WBPSC 2025' },
  { code: 'DN', name: 'Dadra & Nagar Haveli', vacancies: 80, latestResult: null },
  { code: 'DD', name: 'Daman & Diu', vacancies: 60, latestResult: null },
  { code: 'PY', name: 'Puducherry', vacancies: 190, latestResult: null },
];
