// constants/services.js
export const services = [
  {
    id: 'results',
    icon: 'Lightning',
    color: 'var(--accent-violet)',
    title: 'Get Sarkari Results Before Anyone Else',
    description: 'Results for JEE, NEET, UPSC, SSC, Railways, Banking, and 200+ state exams — available the moment they\'re released. Never miss a result again.',
    cta: 'Browse All Results →',
    ctaLink: '/results',
  },
  {
    id: 'jobs',
    icon: 'Briefcase',
    color: 'var(--accent-saffron)',
    title: 'Never Miss a Government Job Opening',
    description: 'Get instant alerts for every new government job vacancy from SSC, UPSC, Railways, State PSC, Banking, Defence, and Teaching sectors.',
    cta: 'View Latest Jobs →',
    ctaLink: '/jobs',
  },
  {
    id: 'tools',
    icon: 'FilePdf',
    color: 'var(--accent-cyan)',
    title: '100% Free PDF Tools — No Signup Needed',
    description: 'Merge, compress, convert, split, rotate, add watermarks, OCR, and e-sign PDFs. 15+ tools available free forever. No limit, no ads, no signup.',
    cta: 'Try PDF Tools →',
    ctaLink: '/tools',
  },
  {
    id: 'news',
    icon: 'Newspaper',
    color: 'var(--accent-emerald)',
    title: 'Verified Education News You Can Trust',
    description: 'No fake news, no clickbait. Curated, fact-checked education and government news updated 24/7. Subscribe to get personalized news in your language.',
    cta: 'Read Latest News →',
    ctaLink: '/news',
  },
  {
    id: 'calendar',
    icon: 'CalendarCheck',
    color: 'var(--accent-gold)',
    title: 'Never Miss an Exam Date Again',
    description: 'Complete calendar with admit card release dates, exam dates, answer keys, and result dates. Countdown timers for every upcoming exam.',
    cta: 'View Exam Calendar →',
    ctaLink: '/calendar',
  },
  {
    id: 'whatsapp',
    icon: 'WhatsappLogo',
    color: '#25D366',
    title: 'Results Straight to Your WhatsApp',
    description: 'Subscribe once. Get instant WhatsApp messages the moment any result is published for your selected exams. Free forever, cancel anytime.',
    cta: 'Subscribe Free →',
    ctaLink: '#whatsapp-cta',
  },
];
