// constants/testimonials.js
export const testimonials = [
  { name: "Rahul Kumar", location: "Varanasi, UP", exam: "JEE", rating: 5,
    text: "ishu.fun showed me my JEE result 2 hours before the official site worked. Incredible!" },
  { name: "Priya Sharma", location: "Jaipur, Rajasthan", exam: "NEET", rating: 5,
    text: "The PDF compression tool saved me so much time for my admit card. Super fast!" },
  { name: "Ankit Yadav", location: "Patna, Bihar", exam: "UPSC", rating: 5,
    text: "Best platform for government exam updates. The WhatsApp alerts are lifesaving." },
  { name: "Meena Patel", location: "Ahmedabad, Gujarat", exam: "SSC", rating: 5,
    text: "I subscribed to WhatsApp alerts for SSC CGL and got notified within 2 minutes!" },
  { name: "Vikash Singh", location: "Lucknow, UP", exam: "Railway", rating: 5,
    text: "Railway exam calendar is perfect. Never miss a date anymore. Love the design!" },
  { name: "Pooja Nair", location: "Kochi, Kerala", exam: "Banking", rating: 5,
    text: "IBPS PO result notification came to my WhatsApp before I even heard from friends." },
  { name: "Suresh Reddy", location: "Hyderabad, TS", exam: "NEET", rating: 5,
    text: "The PDF tools are genuinely free with no watermarks. Rare find on internet!" },
  { name: "Kavya Menon", location: "Bengaluru, KA", exam: "JEE", rating: 5,
    text: "Smooth website, beautiful design, and fast results. ishu.fun is simply the best." },
  { name: "Deepak Maurya", location: "Kanpur, UP", exam: "UPSC", rating: 5,
    text: "News section keeps me updated daily. Very trustworthy and ad-free experience." },
  { name: "Anjali Kumari", location: "Bhagalpur, Bihar", exam: "SSC", rating: 5,
    text: "My WhatsApp group of 50+ friends all use ishu.fun now. We spread the word!" },
  { name: "Rohan Ghosh", location: "Kolkata, WB", exam: "JEE", rating: 5,
    text: "The best sarkari result website I've ever used. Clean, fast, and accurate." },
  { name: "Sneha Verma", location: "Bhopal, MP", exam: "SSC", rating: 5,
    text: "PDF merge tool is amazing! Merged 20 PDFs in seconds. No other site does this free." },
  { name: "Arun Thakur", location: "Ranchi, JH", exam: "Railway", rating: 5,
    text: "Got my RRB NTPC result notification on WhatsApp instantly. Didn't even have to check!" },
  { name: "Divya Rajput", location: "Indore, MP", exam: "Banking", rating: 5,
    text: "The exam calendar saved me from missing my IBPS Clerk admit card download date." },
  { name: "Manish Tiwari", location: "Allahabad, UP", exam: "UPSC", rating: 5,
    text: "ishu.fun's news section is the only news I trust for education updates now." },
];
